# Generated by Django 5.0.4 on 2024-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='currency',
            field=models.CharField(default='UAH', max_length=3),
        ),
    ]
